kind: live
title: ml-recipe-bone-age
id: ml_recipe_bone_age

defaults:
  preset: cpu-small
  life_span: 1d

volumes:
  data:
    remote: storage:${{ flow.project_id }}/data
    mount: /${{ flow.project_id }}/data
    local: data
  dataset:
    remote: storage:${{ flow.project_id }}/dataset
    mount: /${{ flow.project_id }}/dataset
  notebooks:
    remote: storage:ml_recipe_bone_age/notebooks
    mount: /${{ flow.project_id }}/notebooks
    local: notebooks
  src:
    remote: storage:${{ flow.project_id }}/src
    mount: /${{ flow.project_id }}/src
    local: src


images:
  train:
    ref: image:${{ flow.project_id }}:v3
    dockerfile: ${{ flow.workspace }}/docker/train.dockerfile
    context: ${{ flow.workspace }}/
    build_preset: gpu-small-p

jobs:
  prepare_dataset:
    image: ${{ images.train.ref }}
    volumes:
      - ${{ volumes.dataset.ref }}
    bash: |
      wget http://data.neu.ro/bone-age-tiny.zip -O /tmp/bone-age.zip
      unzip -o /tmp/bone-age.zip -d ${{ volumes.dataset.mount }}

  jupyter:
    image: ${{ images.train.ref }}
    name: ${{ flow.title }}-jupyter
    browse: True
    http_port: 8080
    http_auth: False
    volumes:
      - ${{ upload(volumes.notebooks).ref_rw }}
      - ${{ upload(volumes.src).ref }}
      - ${{ volumes.dataset.ref_ro }}
    workdir: /${{ flow.project_id }}
    env:
      PYTHONPATH: /${{ flow.project_id }}
    bash: |
      jupyter notebook \
        --no-browser \
        --ip=0.0.0.0 \
        --port=8080 \
        --allow-root \
        --NotebookApp.token= \
        --NotebookApp.shutdown_no_activity_timeout=7200 \
        --MappingKernelManager.cull_idle_timeout=7200 \
        --notebook-dir=${PYTHONPATH}/notebooks

  train:
    image: ${{ images.train.ref }}
    preset: gpu-k80-small-p
    detach: False
    life_span: 10d
    volumes:
      - ${{ upload(volumes.data).ref }}
      - ${{ volumes.src.ref }}
    workdir: /${{ flow.project_id }}
    env:
      PYTHONPATH: /${{ flow.project_id }}
    bash: |
      python -u ${{ volumes.src.mount }}/train.py \
        --data_dir=${{ volumes.data.mount }}/images \
        --annotation_csv=${{ volumes.data.mount }}/annotations.csv